pkg/models/store.go:16
pkg/proxy/redis/encoder.go:27
pkg/utils/rpc/api.go:33
pkg/utils/resolver.go:65
pkg/proxy/backend.go:150
pkg/proxy/mapper.go:19
pkg/proxy/mapper.go:63
pkg/proxy/stats.go:65
pkg/proxy/stats.go:202

##################################################
#                                                #
#                  Codis-Proxy                   #
#                                                #
##################################################

# Set Codis Product Name/Auth.
product_name = "codis-demo"
product_auth = ""

# Set auth for client session
#   1. product_auth用于codis-dashboard、codis-proxy和codis-server之间的身份验证.
#   2. session_auth与product_auth不同，它需要客户端运行AUTH <PASSWORD> 在处理任何其他命令之前.
session_auth = ""

# Set bind address for admin(rpc), tcp only.
admin_addr = "0.0.0.0:11080"

# Set bind address for proxy, proto_type can be "tcp", "tcp4", "tcp6", "unix" or "unixpacket".
proto_type = "tcp4"
proxy_addr = "0.0.0.0:19000"

# Set jodis address & session timeout
#   1. jodis_name is short for jodis_coordinator_name, only accept "zookeeper" & "etcd".
#   2. jodis_addr is short for jodis_coordinator_addr
#   3. jodis_auth is short for jodis_coordinator_auth, for zookeeper/etcd, "user:password" is accepted.
#   4. proxy will be registered as node:
#        if jodis_compatible = true (not suggested):
#          /zk/codis/db_{PRODUCT_NAME}/proxy-{HASHID} (compatible with Codis2.0)
#        or else
#          /jodis/{PRODUCT_NAME}/proxy-{HASHID}
jodis_name = ""
jodis_addr = ""
jodis_auth = ""
jodis_timeout = "20s"
jodis_compatible = false

proxy_datacenter = ""

# 存活的会话数量[上限]
proxy_max_clients = 1000

# 设置最大堆外内存大小.(0禁用)
proxy_max_offheap_size = "1024mb"

# 设置堆占位符以减少GC频率.
proxy_heap_placeholder = "256mb"

# proxy会主动ping后端的redis服务器,更新状态
backend_ping_period = "5s"

# 设置后端接收缓冲区大小和超时时间
backend_recv_bufsize = "128kb"
backend_recv_timeout = "30s"

# 设置后端发送缓冲区大小和超时时间
backend_send_bufsize = "128kb"
backend_send_timeout = "30s"

# 设置后端pipeline缓冲区大小
backend_max_pipeline = 20480

# 设置后端不读取副本组，默认为false [即会读取slave]
backend_primary_only = false

# 为每个服务器设置后端并行连接
backend_primary_parallel = 1
backend_replica_parallel = 1

# 设置后端tcp保活时间.(0禁用)
backend_keepalive_period = "75s"

# 设置后端数据库数量
backend_number_databases = 16

# 如果客户端长时间没有请求，连接将被关闭.(0 to disable)设置会话recv缓冲区大小和超时时间.
session_recv_bufsize = "128kb"
session_recv_timeout = "30m"

# 设置会话发送缓冲区大小和超时时间.
session_send_bufsize = "64kb"
session_send_timeout = "30s"

# 确保这高于每个管道请求的最大请求数，否则您的客户端可能会被阻塞.
# 设置会话管道缓冲区大小.
session_max_pipeline = 10000

# 设置会话tcp保持时间.(0禁用)
session_keepalive_period = "75s"

# 设置会话对失败敏感.默认为false，代理将向客户端发送错误响应，而不是关闭套接字.
session_break_on_failure = false

# 指标服务器 (such as http://localhost:28000), 代理将报告json格式的指标到指定的服务器在预定义的时期.
metrics_report_server = ""
metrics_report_period = "1s"

# 设置influxdb服务器(如http://localhost:8086)，代理将向influxdb报告指标.
metrics_report_influxdb_server = ""
metrics_report_influxdb_period = "1s"
metrics_report_influxdb_username = ""
metrics_report_influxdb_password = ""
metrics_report_influxdb_database = ""

# 设置statsd服务器(如localhost:8125)，代理将向statsd报告指标.
metrics_report_statsd_server = ""
metrics_report_statsd_period = "1s"
metrics_report_statsd_prefix = ""

